import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/constants/color_constants.dart';
import '../../../../data/models/auction_model.dart';
import '../../../../data/models/car_model.dart';

class BrowseTab extends StatefulWidget {
  const BrowseTab({super.key});

  @override
  State<BrowseTab> createState() => _BrowseTabState();
}

class _BrowseTabState extends State<BrowseTab> {
  // Static mock auction data for guest users
  static final List<Auction> _mockAuctions = [
    Auction(
      id: '1',
      carId: 'car_1',
      sellerId: 'seller_1',
      startingPrice: 450000,
      currentBid: 520000,
      reservePrice: 500000,
      startTime: DateTime.now().subtract(const Duration(days: 2)),
      endTime: DateTime.now().add(const Duration(hours: 18)),
      status: AuctionStatus.live,
      totalBids: 12,
      watchers: List.generate(8, (i) => 'watcher_$i'),
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updatedAt: DateTime.now(),
      car: CarModel(
        id: 'car_1',
        sellerId: 'seller_1',
        sellerName: 'Juan Cruz',
        brand: 'Toyota',
        model: 'Vios',
        variant: '1.3 E MT',
        year: 2020,
        engineSize: '1.3L',
        engineType: EngineType.inline,
        cylinders: 4,
        horsepower: 98,
        torque: 123,
        transmission: TransmissionType.manual,
        transmissionSpeeds: 5,
        driveType: DriveType.fwd,
        fuelType: FuelType.gasoline,
        fuelConsumption: 6.2,
        bodyType: BodyType.sedan,
        doors: 4,
        seats: 5,
        curbWeight: 1045,
        grossWeight: 1500,
        cargoCapacity: 450,
        length: 4425,
        width: 1730,
        height: 1475,
        wheelbase: 2550,
        color: 'White',
        paintType: PaintType.solid,
        rimSize: 15,
        rimType: RimType.alloy,
        tireCondition: TireCondition.good,
        condition: CarCondition.used,
        mileage: 45000,
        numberOfOwners: 1,
        hasAccidentHistory: false,
        floodDamage: false,
        serviceHistoryComplete: true,
        location: const CarLocation(city: 'Manila', province: 'Metro Manila'),
        plateNumber: 'ABC1234',
        orcrNumber: 'OR123456789',
        registrationStatus: RegistrationStatus.current,
        emissionTestValid: true,
        comprehensiveInsurance: true,
        description: 'Well-maintained Toyota Vios, single owner, complete service records',
        images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800'],
        categorizedImages: {},
        status: ListingStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now(),
      ),
    ),
    Auction(
      id: '2',
      carId: 'car_2',
      sellerId: 'seller_2',
      startingPrice: 850000,
      currentBid: 920000,
      reservePrice: 900000,
      startTime: DateTime.now().subtract(const Duration(days: 1)),
      endTime: DateTime.now().add(const Duration(hours: 12)),
      status: AuctionStatus.live,
      totalBids: 18,
      watchers: List.generate(15, (i) => 'watcher_$i'),
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      updatedAt: DateTime.now(),
      car: CarModel(
        id: 'car_2',
        sellerId: 'seller_2',
        sellerName: 'Maria Santos',
        brand: 'Honda',
        model: 'Civic',
        variant: '1.8 S CVT',
        year: 2019,
        engineSize: '1.8L',
        engineType: EngineType.inline,
        cylinders: 4,
        horsepower: 141,
        torque: 174,
        transmission: TransmissionType.cvt,
        transmissionSpeeds: 0,
        driveType: DriveType.fwd,
        fuelType: FuelType.gasoline,
        fuelConsumption: 7.1,
        bodyType: BodyType.sedan,
        doors: 4,
        seats: 5,
        curbWeight: 1260,
        grossWeight: 1700,
        cargoCapacity: 519,
        length: 4648,
        width: 1799,
        height: 1416,
        wheelbase: 2700,
        color: 'Gray',
        paintType: PaintType.metallic,
        rimSize: 17,
        rimType: RimType.alloy,
        tireCondition: TireCondition.good,
        condition: CarCondition.used,
        mileage: 38000,
        numberOfOwners: 1,
        hasAccidentHistory: false,
        floodDamage: false,
        serviceHistoryComplete: true,
        location: const CarLocation(city: 'Quezon City', province: 'Metro Manila'),
        plateNumber: 'XYZ9876',
        orcrNumber: 'OR987654321',
        registrationStatus: RegistrationStatus.current,
        emissionTestValid: true,
        comprehensiveInsurance: true,
        description: 'Honda Civic in excellent condition, low mileage, garage kept',
        images: ['https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800'],
        categorizedImages: {},
        status: ListingStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        updatedAt: DateTime.now(),
      ),
    ),
    Auction(
      id: '3',
      carId: 'car_3',
      sellerId: 'seller_3',
      startingPrice: 1200000,
      currentBid: 1350000,
      reservePrice: 1300000,
      startTime: DateTime.now().subtract(const Duration(hours: 8)),
      endTime: DateTime.now().add(const Duration(hours: 40)),
      status: AuctionStatus.live,
      totalBids: 24,
      watchers: List.generate(22, (i) => 'watcher_$i'),
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now(),
      car: CarModel(
        id: 'car_3',
        sellerId: 'seller_3',
        sellerName: 'Pedro Reyes',
        brand: 'Mazda',
        model: 'CX-5',
        variant: '2.5 AWD Sport',
        year: 2021,
        engineSize: '2.5L',
        engineType: EngineType.inline,
        cylinders: 4,
        horsepower: 187,
        torque: 252,
        transmission: TransmissionType.automatic,
        transmissionSpeeds: 6,
        driveType: DriveType.awd,
        fuelType: FuelType.gasoline,
        fuelConsumption: 8.5,
        bodyType: BodyType.suv,
        doors: 5,
        seats: 5,
        curbWeight: 1620,
        grossWeight: 2100,
        cargoCapacity: 1342,
        length: 4575,
        width: 1842,
        height: 1680,
        wheelbase: 2700,
        color: 'Red',
        paintType: PaintType.metallic,
        rimSize: 19,
        rimType: RimType.alloy,
        tireCondition: TireCondition.newTires,
        condition: CarCondition.almostNew,
        mileage: 15000,
        numberOfOwners: 1,
        hasAccidentHistory: false,
        floodDamage: false,
        serviceHistoryComplete: true,
        location: const CarLocation(city: 'Makati', province: 'Metro Manila'),
        plateNumber: 'DEF5678',
        orcrNumber: 'OR456789123',
        registrationStatus: RegistrationStatus.current,
        emissionTestValid: true,
        comprehensiveInsurance: true,
        description: 'Almost new Mazda CX-5, low mileage, fully loaded variant',
        images: ['https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800'],
        categorizedImages: {},
        status: ListingStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
      ),
    ),
    Auction(
      id: '4',
      carId: 'car_4',
      sellerId: 'seller_4',
      startingPrice: 680000,
      currentBid: 750000,
      reservePrice: 720000,
      startTime: DateTime.now().subtract(const Duration(days: 3)),
      endTime: DateTime.now().add(const Duration(hours: 6)),
      status: AuctionStatus.live,
      totalBids: 16,
      watchers: List.generate(11, (i) => 'watcher_$i'),
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      updatedAt: DateTime.now(),
      car: CarModel(
        id: 'car_4',
        sellerId: 'seller_4',
        sellerName: 'Ana Garcia',
        brand: 'Mitsubishi',
        model: 'Montero Sport',
        variant: 'GLS 4x2 AT',
        year: 2018,
        engineSize: '2.4L',
        engineType: EngineType.inline,
        cylinders: 4,
        horsepower: 178,
        torque: 430,
        transmission: TransmissionType.automatic,
        transmissionSpeeds: 8,
        driveType: DriveType.rwd,
        fuelType: FuelType.diesel,
        fuelConsumption: 9.2,
        bodyType: BodyType.suv,
        doors: 5,
        seats: 7,
        curbWeight: 2010,
        grossWeight: 2800,
        cargoCapacity: 1045,
        length: 4785,
        width: 1815,
        height: 1800,
        wheelbase: 2800,
        color: 'Black',
        paintType: PaintType.solid,
        rimSize: 18,
        rimType: RimType.alloy,
        tireCondition: TireCondition.good,
        condition: CarCondition.used,
        mileage: 62000,
        numberOfOwners: 2,
        hasAccidentHistory: false,
        floodDamage: false,
        serviceHistoryComplete: true,
        location: const CarLocation(city: 'Pasig', province: 'Metro Manila'),
        plateNumber: 'GHI3456',
        orcrNumber: 'OR345678912',
        registrationStatus: RegistrationStatus.current,
        emissionTestValid: true,
        comprehensiveInsurance: true,
        description: 'Reliable family SUV, well-maintained, second owner',
        images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800'],
        categorizedImages: {},
        status: ListingStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        updatedAt: DateTime.now(),
      ),
    ),
    Auction(
      id: '5',
      carId: 'car_5',
      sellerId: 'seller_5',
      startingPrice: 320000,
      currentBid: 365000,
      reservePrice: 350000,
      startTime: DateTime.now().subtract(const Duration(hours: 16)),
      endTime: DateTime.now().add(const Duration(hours: 32)),
      status: AuctionStatus.live,
      totalBids: 9,
      watchers: List.generate(6, (i) => 'watcher_$i'),
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now(),
      car: CarModel(
        id: 'car_5',
        sellerId: 'seller_5',
        sellerName: 'Luis Mendoza',
        brand: 'Suzuki',
        model: 'Swift',
        variant: '1.2 GL MT',
        year: 2019,
        engineSize: '1.2L',
        engineType: EngineType.inline,
        cylinders: 4,
        horsepower: 82,
        torque: 113,
        transmission: TransmissionType.manual,
        transmissionSpeeds: 5,
        driveType: DriveType.fwd,
        fuelType: FuelType.gasoline,
        fuelConsumption: 5.1,
        bodyType: BodyType.hatchback,
        doors: 5,
        seats: 5,
        curbWeight: 890,
        grossWeight: 1300,
        cargoCapacity: 265,
        length: 3845,
        width: 1735,
        height: 1480,
        wheelbase: 2450,
        color: 'Blue',
        paintType: PaintType.metallic,
        rimSize: 15,
        rimType: RimType.alloy,
        tireCondition: TireCondition.good,
        condition: CarCondition.used,
        mileage: 51000,
        numberOfOwners: 1,
        hasAccidentHistory: false,
        floodDamage: false,
        serviceHistoryComplete: true,
        location: const CarLocation(city: 'Taguig', province: 'Metro Manila'),
        plateNumber: 'JKL7890',
        orcrNumber: 'OR789012345',
        registrationStatus: RegistrationStatus.current,
        emissionTestValid: true,
        comprehensiveInsurance: false,
        description: 'Fuel-efficient city car, perfect for daily commute',
        images: ['https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800'],
        categorizedImages: {},
        status: ListingStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
      ),
    ),
    Auction(
      id: '6',
      carId: 'car_6',
      sellerId: 'seller_6',
      startingPrice: 1580000,
      currentBid: 1720000,
      reservePrice: 1650000,
      startTime: DateTime.now().subtract(const Duration(hours: 4)),
      endTime: DateTime.now().add(const Duration(hours: 44)),
      status: AuctionStatus.live,
      totalBids: 31,
      watchers: List.generate(28, (i) => 'watcher_$i'),
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      updatedAt: DateTime.now(),
      car: CarModel(
        id: 'car_6',
        sellerId: 'seller_6',
        sellerName: 'Rosa Diaz',
        brand: 'Ford',
        model: 'Ranger',
        variant: 'Wildtrak 4x4 AT',
        year: 2020,
        engineSize: '2.0L',
        engineType: EngineType.inline,
        cylinders: 4,
        horsepower: 210,
        torque: 500,
        transmission: TransmissionType.automatic,
        transmissionSpeeds: 10,
        driveType: DriveType.fourWd,
        fuelType: FuelType.diesel,
        fuelConsumption: 10.5,
        bodyType: BodyType.pickup,
        doors: 4,
        seats: 5,
        curbWeight: 2165,
        grossWeight: 3200,
        cargoCapacity: 1180,
        towingCapacity: 3500,
        groundClearance: 232,
        length: 5362,
        width: 1860,
        height: 1848,
        wheelbase: 3220,
        color: 'Silver',
        paintType: PaintType.metallic,
        rimSize: 18,
        rimType: RimType.alloy,
        tireCondition: TireCondition.good,
        condition: CarCondition.used,
        mileage: 42000,
        numberOfOwners: 1,
        hasAccidentHistory: false,
        floodDamage: false,
        serviceHistoryComplete: true,
        location: const CarLocation(city: 'Paranaque', province: 'Metro Manila'),
        plateNumber: 'MNO2468',
        orcrNumber: 'OR246813579',
        registrationStatus: RegistrationStatus.current,
        emissionTestValid: true,
        comprehensiveInsurance: true,
        description: 'Premium pickup truck, top of the line variant, excellent condition',
        images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800'],
        categorizedImages: {},
        status: ListingStatus.active,
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        updatedAt: DateTime.now(),
      ),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: [
        SliverToBoxAdapter(
          child: Container(
            margin: const EdgeInsets.all(16),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.orange[50],
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.orange[200]!),
            ),
            child: Row(
              children: [
                Icon(Icons.info_outline, color: Colors.orange[700]),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    'Limited preview mode. Register to browse all listings and place bids.',
                    style: TextStyle(
                      color: Colors.orange[900],
                      fontSize: 14,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
        SliverPadding(
          padding: const EdgeInsets.all(16),
          sliver: SliverGrid(
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
              mainAxisSpacing: 16,
              crossAxisSpacing: 16,
              childAspectRatio: 0.7,
            ),
            delegate: SliverChildBuilderDelegate(
              (context, index) {
                final auction = _mockAuctions[index];
                final car = auction.car!;
                return Card(
                  clipBehavior: Clip.antiAlias,
                  child: InkWell(
                    onTap: () {
                      _showRegisterDialog(context);
                    },
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(
                          flex: 3,
                          child: Stack(
                            fit: StackFit.expand,
                            children: [
                              car.images.isNotEmpty
                                  ? Image.network(
                                      car.images.first,
                                      fit: BoxFit.cover,
                                      errorBuilder: (_, __, ___) => Container(
                                        color: Colors.grey[300],
                                        child: const Icon(Icons.directions_car, size: 48),
                                      ),
                                    )
                                  : Container(
                                      color: Colors.grey[300],
                                      child: const Icon(Icons.directions_car, size: 48),
                                    ),
                              Positioned(
                                top: 8,
                                right: 8,
                                child: Container(
                                  padding: const EdgeInsets.symmetric(
                                    horizontal: 8,
                                    vertical: 4,
                                  ),
                                  decoration: BoxDecoration(
                                    color: Colors.red,
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  child: const Text(
                                    'LIVE',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 11,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        Expanded(
                          flex: 2,
                          child: Padding(
                            padding: const EdgeInsets.all(8),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  '${car.year} ${car.brand} ${car.model}',
                                  style: const TextStyle(
                                    fontWeight: FontWeight.bold,
                                    fontSize: 13,
                                  ),
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                                const SizedBox(height: 4),
                                Text(
                                  'Current Bid: ₱${_formatPrice(auction.currentBid)}',
                                  style: TextStyle(
                                    color: ColorConstants.primaryGreen,
                                    fontWeight: FontWeight.bold,
                                    fontSize: 12,
                                  ),
                                ),
                                const SizedBox(height: 4),
                                Row(
                                  children: [
                                    Icon(Icons.gavel, size: 14, color: Colors.grey[600]),
                                    const SizedBox(width: 4),
                                    Text(
                                      '${auction.totalBids} bids',
                                      style: TextStyle(
                                        color: Colors.grey[600],
                                        fontSize: 11,
                                      ),
                                    ),
                                    const SizedBox(width: 12),
                                    Icon(Icons.visibility, size: 14, color: Colors.grey[600]),
                                    const SizedBox(width: 4),
                                    Text(
                                      '${auction.watchers.length} watching',
                                      style: TextStyle(
                                        color: Colors.grey[600],
                                        fontSize: 11,
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
              childCount: _mockAuctions.length,
            ),
          ),
        ),
      ],
    );
  }

  String _formatPrice(double price) {
    if (price >= 1000000) {
      return '${(price / 1000000).toStringAsFixed(1)}M';
    } else if (price >= 1000) {
      return '${(price / 1000).toStringAsFixed(0)}K';
    }
    return price.toStringAsFixed(0);
  }

  void _showRegisterDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Account Required'),
        content: const Text(
          'To view auction details and place bids, you need to:\n\n'
          '• Register for a new account\n'
          '• Login if you already have an account\n'
          '• Check your account status in the Account tab',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Okay'),
          ),
        ],
      ),
    );
  }
}
