class CarFeatures {
  static const List<String> standardFeatures = [
    'Air Conditioning',
    'Power Steering',
    'Anti-lock Braking System (ABS)',
    'Airbags',
    'Reverse Camera',
    'Bluetooth Connectivity',
    'USB Ports',
    'Touchscreen Infotainment',
    'Apple CarPlay',
    'Android Auto',
    'Cruise Control',
    'Keyless Entry',
    'Push Start Button',
    'Power Windows',
    'Power Door Locks',
    'Electric Side Mirrors',
    'Fog Lights',
    'LED Headlights',
    'Sunroof/Moonroof',
    'Leather Seats',
    'Heated Seats',
    'Ventilated Seats',
    'Memory Seats',
    'Power Adjustable Seats',
    'Rear Parking Sensors',
    'Front Parking Sensors',
    '360-degree Camera',
    'Blind Spot Monitoring',
    'Lane Departure Warning',
    'Adaptive Cruise Control',
    'Automatic Emergency Braking',
    'Hill Start Assist',
    'Traction Control',
    'Stability Control',
    'All-Wheel Drive (AWD)',
    '4-Wheel Drive (4WD)',
    'Paddle Shifters',
    'Sport Mode',
    'Eco Mode',
    'Navigation System',
    'Premium Sound System',
    'Wireless Charging',
    'Automatic Climate Control',
    'Dual-Zone Climate Control',
    'Rear AC Vents',
    'Rain Sensing Wipers',
    'Auto-dimming Mirrors',
    'Roof Rails',
    'Alloy Wheels',
    'Spare Tire',
  ];
}
