class PhilippineCities {
  static const List<String> cities = [
    'Manila',
    'Quezon City',
    'Caloocan',
    'Las Piñas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Parañaque',
    'Pasay',
    'Pasig',
    'Pateros',
    'San Juan',
    'Taguig',
    'Valenzuela',
    'Antipolo',
    'Bacoor',
    'Baguio',
    'Bacolod',
    'Batangas City',
    'Cagayan de Oro',
    'Calamba',
    'Cebu City',
    'Cotabato City',
    'Davao City',
    'General Santos',
    'Iligan',
    'Iloilo City',
    'Lapu-Lapu',
    'Las Piñas',
    'Legazpi',
    'Lucena',
    'Mandaue',
    'Naga',
    'Olongapo',
    'Ormoc',
    'Puerto Princesa',
    'San Fernando',
    'Tagaytay',
    'Tacloban',
    'Zamboanga City',
  ];
}
