/// Mapping of Philippine provinces to their cities/municipalities
/// This provides a more accurate location selection experience
class PhilippineProvinceCities {
  static const Map<String, List<String>> provinceCityMap = {
    'Metro Manila': [
      'Manila',
      'Quezon City',
      'Caloocan',
      'Las Piñas',
      'Makati',
      'Malabon',
      'Mandaluyong',
      'Marikina',
      'Muntinlupa',
      'Navotas',
      'Parañaque',
      'Pasay',
      'Pasig',
      'Pateros',
      'San Juan',
      'Taguig',
      'Valenzuela',
    ],
    'Cavite': [
      'Bacoor',
      'Cavite City',
      'Dasmariñas',
      'Imus',
      'Tagaytay',
      'Trece Martires',
      'General Trias',
      'Silang',
      'Rosario',
      'Tanza',
    ],
    'Laguna': [
      'Calamba',
      'San Pablo',
      'Biñan',
      'Santa Rosa',
      'Cabuyao',
      'Los Baños',
      'Bay',
      'Sta. Cruz',
    ],
    'Batangas': [
      'Batangas City',
      'Lipa',
      'Tanauan',
      'Sto. Tomas',
      'Lemery',
      'Taal',
      'Balayan',
      'Nasugbu',
    ],
    'Rizal': [
      'Antipolo',
      'Cainta',
      'Taytay',
      'Binangonan',
      'Angono',
      'Rodriguez',
      'San Mateo',
      'Morong',
    ],
    'Bulacan': [
      'Malolos',
      'Meycauayan',
      'San Jose del Monte',
      'Marilao',
      'Bocaue',
      'Balagtas',
      'Guiguinto',
      'Plaridel',
    ],
    'Pampanga': [
      'San Fernando',
      'Angeles',
      'Mabalacat',
      'Porac',
      'Floridablanca',
      'Guagua',
      'Mexico',
      'Arayat',
    ],
    'Cebu': [
      'Cebu City',
      'Mandaue',
      'Lapu-Lapu',
      'Talisay',
      'Toledo',
      'Danao',
      'Carcar',
      'Naga',
    ],
    'Davao del Sur': [
      'Davao City',
      'Digos',
      'Tagum',
      'Panabo',
      'Samal',
      'Mati',
    ],
    'Iloilo': [
      'Iloilo City',
      'Passi',
      'Oton',
      'Pavia',
      'Leganes',
      'Santa Barbara',
      'Cabatuan',
    ],
    'Negros Occidental': [
      'Bacolod',
      'Silay',
      'Talisay',
      'Victorias',
      'Bago',
      'Cadiz',
      'Sagay',
      'San Carlos',
    ],
    'Pangasinan': [
      'Dagupan',
      'Urdaneta',
      'San Carlos',
      'Alaminos',
      'Lingayen',
      'Bayambang',
      'Malasiqui',
    ],
    'Benguet': [
      'Baguio',
      'La Trinidad',
      'Itogon',
      'Tuba',
      'Sablan',
      'Tublay',
    ],
    'La Union': [
      'San Fernando',
      'Bauang',
      'Agoo',
      'Aringay',
      'Bacnotan',
      'San Juan',
    ],
    'Albay': [
      'Legazpi',
      'Tabaco',
      'Ligao',
      'Daraga',
      'Polangui',
      'Guinobatan',
    ],
    'Camarines Sur': [
      'Naga',
      'Iriga',
      'Pili',
      'Magarao',
      'Canaman',
      'Bombon',
    ],
    'Palawan': [
      'Puerto Princesa',
      'Coron',
      'El Nido',
      'Taytay',
      'Roxas',
      'San Vicente',
    ],
    'Quezon': [
      'Lucena',
      'Tayabas',
      'Sariaya',
      'Candelaria',
      'Tiaong',
      'Lucban',
    ],
    'Leyte': [
      'Tacloban',
      'Ormoc',
      'Baybay',
      'Palo',
      'Tanauan',
      'Dulag',
    ],
    'Zamboanga del Sur': [
      'Zamboanga City',
      'Pagadian',
      'Dipolog',
      'Dapitan',
    ],
    'Cagayan': [
      'Tuguegarao',
      'Aparri',
      'Lal-lo',
      'Gattaran',
      'Sanchez Mira',
    ],
    'Isabela': [
      'Ilagan',
      'Santiago',
      'Cauayan',
      'Roxas',
      'Cabagan',
    ],
    'Nueva Ecija': [
      'Cabanatuan',
      'Gapan',
      'San Jose',
      'Palayan',
      'Science City of Muñoz',
    ],
    'Tarlac': [
      'Tarlac City',
      'Concepcion',
      'Capas',
      'Bamban',
      'Paniqui',
    ],
    'Zambales': [
      'Olongapo',
      'Subic',
      'Iba',
      'San Antonio',
      'Castillejos',
    ],
    'Bataan': [
      'Balanga',
      'Mariveles',
      'Dinalupihan',
      'Hermosa',
      'Orani',
    ],
    'Bohol': [
      'Tagbilaran',
      'Ubay',
      'Talibon',
      'Trinidad',
      'Jagna',
    ],
    'Misamis Oriental': [
      'Cagayan de Oro',
      'Gingoog',
      'El Salvador',
      'Jasaan',
      'Villanueva',
    ],
    'South Cotabato': [
      'General Santos',
      'Koronadal',
      'Polomolok',
      'Tupi',
      'Tampakan',
    ],
    'Agusan del Norte': [
      'Butuan',
      'Cabadbaran',
      'Buenavista',
      'Nasipit',
    ],
    'Lanao del Norte': [
      'Iligan',
      'Tubod',
      'Kauswagan',
      'Bacolod',
    ],
    // Add remaining provinces with at least their capital/major city
    'Abra': ['Bangued', 'Lagangilang', 'Pidigan'],
    'Agusan del Sur': ['Bayugan', 'Prosperidad', 'San Francisco'],
    'Aklan': ['Kalibo', 'Ibajay', 'Numancia'],
    'Antique': ['San Jose de Buenavista', 'Sibalom', 'Culasi'],
    'Apayao': ['Kabugao', 'Luna', 'Pudtol'],
    'Aurora': ['Baler', 'Casiguran', 'Dingalan'],
    'Basilan': ['Isabela City', 'Lamitan'],
    'Batanes': ['Basco', 'Ivana', 'Uyugan'],
    'Biliran': ['Naval', 'Almeria', 'Kawayan'],
    'Bukidnon': ['Malaybalay', 'Valencia', 'Manolo Fortich'],
    'Camarines Norte': ['Daet', 'Jose Panganiban', 'Labo'],
    'Camiguin': ['Mambajao', 'Sagay', 'Guinsiliban'],
    'Capiz': ['Roxas City', 'Panay', 'Pontevedra'],
    'Catanduanes': ['Virac', 'Bato', 'San Andres'],
    'Cotabato': ['Kidapawan', 'Midsayap', 'Kabacan'],
    'Davao de Oro': ['Nabunturan', 'Monkayo', 'Montevista'],
    'Davao del Norte': ['Tagum', 'Panabo', 'Samal Island Garden City'],
    'Davao Occidental': ['Malita', 'Santa Maria', 'Don Marcelino'],
    'Davao Oriental': ['Mati', 'Baganga', 'Manay'],
    'Dinagat Islands': ['San Jose', 'Basilisa', 'Dinagat'],
    'Eastern Samar': ['Borongan', 'Guiuan', 'Oras'],
    'Guimaras': ['Jordan', 'Nueva Valencia', 'Buenavista'],
    'Ifugao': ['Lagawe', 'Banaue', 'Mayoyao'],
    'Ilocos Norte': ['Laoag', 'Batac', 'Paoay'],
    'Ilocos Sur': ['Vigan', 'Candon', 'Bantay'],
    'Kalinga': ['Tabuk', 'Pinukpuk', 'Pasil'],
    'Maguindanao': ['Shariff Aguak', 'Cotabato City', 'Datu Odin Sinsuat'],
    'Marinduque': ['Boac', 'Gasan', 'Santa Cruz'],
    'Masbate': ['Masbate City', 'Aroroy', 'Placer'],
    'Misamis Occidental': ['Oroquieta', 'Ozamiz', 'Tangub'],
    'Mountain Province': ['Bontoc', 'Sagada', 'Tadian'],
    'Negros Oriental': ['Dumaguete', 'Bayawan', 'Bais'],
    'Northern Samar': ['Catarman', 'Allen', 'Laoang'],
    'Nueva Vizcaya': ['Bayombong', 'Bambang', 'Solano'],
    'Occidental Mindoro': ['Mamburao', 'Sablayan', 'San Jose'],
    'Oriental Mindoro': ['Calapan', 'Puerto Galera', 'Bongabong'],
    'Quirino': ['Cabarroguis', 'Diffun', 'Saguday'],
    'Romblon': ['Romblon', 'Odiongan', 'San Agustin'],
    'Samar': ['Catbalogan', 'Calbayog', 'Basey'],
    'Sarangani': ['Alabel', 'Glan', 'Malapatan'],
    'Siquijor': ['Siquijor', 'Larena', 'Lazi'],
    'Sorsogon': ['Sorsogon City', 'Irosin', 'Bulan'],
    'Southern Leyte': ['Maasin', 'Sogod', 'Bontoc'],
    'Sultan Kudarat': ['Isulan', 'Tacurong', 'Lambayong'],
    'Sulu': ['Jolo', 'Parang', 'Siasi'],
    'Surigao del Norte': ['Surigao City', 'Siargao', 'Dapa'],
    'Surigao del Sur': ['Tandag', 'Bislig', 'Lianga'],
    'Tawi-Tawi': ['Bongao', 'Simunul', 'Languyan'],
    'Zamboanga del Norte': ['Dipolog', 'Dapitan', 'Sindangan'],
    'Zamboanga Sibugay': ['Ipil', 'Alicia', 'Buug'],
  };

  /// Get cities for a specific province
  static List<String> getCitiesForProvince(String? province) {
    if (province == null) return [];
    return provinceCityMap[province] ?? [];
  }

  /// Get all provinces
  static List<String> get provinces {
    return provinceCityMap.keys.toList()..sort();
  }

  /// Get all cities
  static List<String> get allCities {
    return provinceCityMap.values.expand((cities) => cities).toList()..sort();
  }

  /// Check if a city belongs to a province
  static bool isCityInProvince(String city, String province) {
    final cities = provinceCityMap[province];
    return cities?.contains(city) ?? false;
  }
}
